### ISSUE TITLE
Small feature ideas

### ISSUE THREAD

**Issue by manonbertin** [Mazahir26/koduko#13]
Hi and thanks for this great app !

 I was using another one before and migrated to yours, but I miss some little things for my experience to be perfect.

-  I saw that it was requested before for durations over 30 minutes, but it would be great to put custom durations on tasks (even if it stays short). Sometimes I want 3 or 7 minutes-long tasks and can not do that. 

- Would it be possible to add a way to see the whole duration of a routine ? It could be nice to know how long is a full routine before starting it. (In the Today's Routines pages, for example)

- Finally, and it is very linked to the previous suggestion, would it be possible to display the remaining time for a routine on the routine page (It is shown for the current habit but not for the routine).

Thank you very much for reading my message, keep up the great work !

**Comment by Mazahir26** [comment]
Hey!

- I will try to add custom duration selector, in the next update.
- To add the whole duration in the routine tile is an amazing idea, Will surely implement it.
- Same goes for showing the remaining time.

Thank you for your kind words!
Hope you enjoy the app.
