### ISSUE TITLE
Dynamic colors

### ISSUE THREAD

**Issue by muznyo** [Mazahir26/koduko#17]
**Is your feature request related to a problem? Please describe.**
You implemented Material You, but it doesn't follow system colors.

**Describe the solution you'd like**
Add an option to use system colors.

**Comment by Mazahir26** [comment]
Hey!

Thanks for trying out koduko.

Yep, i am aware that the app doesn't support dynamic color. Frankly, because i didn't know how to add that feature,
But i have found a package which can help me achieve it so will be adding it in the next update.

Thank you 😁
