### ISSUE TITLE
Feature Request/Suggestion

### ISSUE THREAD

**Issue by haildriver** [Mazahir26/koduko#19]
1. **Back up (Import/Export) data**
2. **Heat maps** like in github to track progress.
3. **Custom Progress** Some tasks progress like drinking water can be tracked per glass while others eg. meditation can be time based, so custom unit progress tracker.
4.  **Add Habits Under single Tab** It takes multiple click to add one task, it can be  managed in one place.
5. **Reminder when you're overdue on task** When meditating or other task, reminder when times up. You can add promodo clock.
6. **Popup notes** to recollect thought after task is done.
7. **Subtask** within habits like to-do list within habit.
Thanks for already such a great app.

**Comment by Mazahir26** [comment]
Firstly, thank you for trying out koduko.

Wow, you have a lot of feature requests. I don't think I can add all the requested features, and it will take some time for the next update.

Thank you.

**Comment by Mazahir26** [comment]
Hey, 

An update: I have given thought to your feature list and feel that the notes and subtasks will make the app complex.

I feel that this app should remain simple and with a single purpose which is to remind you about your daily tasks or routines.
I hope you understand my point of view.

Will close this issue now.
Thank you.
