### ISSUE TITLE
versions do not match

### ISSUE THREAD

**Issue by ghost** [Mazahir26/koduko#2]
in app:

![IMG_20220805_235515.jpg](https://user-images.githubusercontent.com/71558811/183162669-ce6a1c32-b544-4555-87e1-24fe30eb2882.jpg)

in app info (settings): 

![IMG_20220805_235534.jpg](https://user-images.githubusercontent.com/71558811/183163165-19408b75-76b0-44c6-a171-3afa05392c3a.jpg)

(I assume, _from release's package name_, it should be ```0.1.0``` or ```1.0.0```)

**Comment by Mazahir26** [comment]
Thanks for pointing that out.

I wasn't aware of that, will fix it in the next update.

Thank you!

**Comment by ghost** [comment]
> Thanks for pointing that out.
> 
> I wasn't aware of that, will fix it in the next update.
> 
> Thank you!

You're welcome.

Also, may I open a PR to update README.md (such as punctuation fixes and better understandable readme)

**Comment by Mazahir26** [comment]
> > Thanks for pointing that out.
> > I wasn't aware of that, will fix it in the next update.
> > Thank you!
> 
> You're welcome.
> 
> Also, may I open a PR to update README.md (such as punctuation fixes and better understandable readme)

Sure, that would be very helpful.
