### ISSUE TITLE
Dark Theme Not Applying

### ISSUE THREAD

**Issue by Murilogs1910** [Mazahir26/koduko#24]
**Describe the bug**
The app is stuck on light mode. Choosing to follow the system's theme or manually opting for the dark change nothing. Restarting the app or reinstalling it didn't change a thing either.

**To Reproduce**
1. Open the app
2. Make sure it should be on dark mode
3. Look at the app

**Expected behavior**
Dark mode.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Doubt it matters
 - OS: Android 11 OneUI 3.1
 - Version: 1.0.2 (2001)

**Additional context**
Downloaded from IzzyOnDroid, but since it server the apk from GitHub, I doubt it matters.

**Comment by Mazahir26** [comment]
Apologies for the oversight. I didn't thoroughly test everything before the app release. I'll be pushing an update soon to address the bug. 
Thank you!

**Comment by Mazahir26** [comment]
Hey! This issue has been fixed in the latest release #27. So, I'm closing this issue.

Thank You!
