### ISSUE TITLE
Task duration timer in notifications and notification at the end of a task's time

### ISSUE THREAD

**Issue by Terkyz** [Mazahir26/koduko#3]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
1. When a task's timer time reaches 0, a notification or alarm sounds to let the user know the time is up

2. A notification bar with the timer of said task in the notifications panel.

**Describe alternatives you've considered**
1. IDK.

**Additional context**
Nothing.

**Comment by Mazahir26** [comment]
Currently working on that exact feature and many more.
Will close the issue as soon as the update is released.

Thank you for checking out my project.

**Comment by Mazahir26** [comment]
Have added the features in main branch. 
Yet to release the update.😁
